# THIS MUST ALWAYS BE ODD
SCREEN_WIDTH = 25
SCREEN_HEIGHT = 25

MAP_WIDTH = 51
MAP_HEIGHT = 51

STAT_LOG_HEIGHT = SCREEN_HEIGHT
STAT_LOG_WIDTH = 11

MSG_LOG_WIDTH = SCREEN_WIDTH + STAT_LOG_WIDTH
MSG_LOG_HEIGHT = 30

# [A-Za-z] is 52 letters for inventory slots
INV_MAX = 52

NUM_RENDER_LAYERS = 5
FRONT = 4
MID_FRONT = 3
MID = 2
MID_BACK = 1
BACK = 0
RENDER_LAYERS = [BACK, MID_BACK, MID, MID_FRONT, FRONT]


def in_bounds(x, y):
    return 0 <= x < MAP_WIDTH and 0 <= y < MAP_HEIGHT
